### ISSUE TITLE
Installation issue due to flask version

### ISSUE THREAD

**Issue by 99MengXin** [liuyug/flask-mdict#6]
Thanks for creating this excellent MDX dictionary project. I wanted to share some tips for installation and use.

I've noticed a bug in the release and master versions. The `requirements.txt` file doesn't specify the version of Flask, so your system may download the latest version (2.x) of Flask. However, this can cause an error when you run the code, leading to a crash.

The solution is simple: you just need to make a change to the `view.py` file located in `/flask-mdict-master/flask_mdict`.

In this file, replace all instances of `attachment_filename` with `download_name` (there should be two places).

See below link for more details.
[TypeError: send_file() got an unexpected keyword argument 'attachment_filename' · Issue #4753 · pallets/flask](https://github.com/pallets/flask/issues/4753)

**Comment by liuyug** [comment]
thanks. have fixed

**Comment by 99MengXin** [comment]
Thank you. The installation is normal now.
